version: "3.8"
services:
    app:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - ./data:/app/data
        environment:
            - NODE_ENV=development
        command: npm run start
