version: "3.8"
services:
    app:
        build: .
        ports:
            - "8080:8080"
        environment:
            - NODE_ENV=development
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        volumes:
            - app_data:/app/data

volumes:
    app_data:
